### PR TITLE
Update to use Commonmark 2.0

### PR DESCRIPTION
**Pull request by joshbruce**
This is a work in progress PR for verifying abbreviations will work with Commonmark 2.*.

https://github.com/8fold/commonmark-accordions will also need to be verified and updated accordingly.

### CODE REVIEW

**Comment by joshbruce** [comment]
Hey @Ambient-Impact wanted to give you a chance to review these changes for possible impact to you.

All of the tests still pass and no new tests were added.

It looks like CommonMark 2+ changes the permalink header convention thought.

**Comment by Ambient-Impact** [comment]
> Hey @Ambient-Impact wanted to give you a chance to review these changes for possible impact to you.
> 
> All of the tests still pass and no new tests were added.
> 
> It looks like CommonMark 2+ changes the permalink header convention though.

I appreciate the heads up. I'm up to my eyeballs with work at the moment as we launched our project a few weeks ago, so I don't have time right now to look at all of this. Since we use the Markdown Drupal module and it's rather slow to update its support of CommonMark versions, I doubt we'll be moving to CommonMark 2 anytime soon. 😅 On the plus side, the many abbreviations are working pretty well after launch.

**Comment by joshbruce** [comment]
Glad the project is progressing!

I'll probably go ahead and merge and release. It'll be a new major, so, should be easy to deal there. 😃 

Thanks for all the contributions and using the project!

**Comment by Ambient-Impact** [comment]
> Glad the project is progressing!

Thanks! If you want to see the output of this extension along with our auto-matching stuff, check [this article](https://omnipedia.app/wiki/2049/10/01/Global_Secure_Information_Exchange_System) out.

> I'll probably go ahead and merge and release. It'll be a new major, so, should be easy to deal there. 😃
> 
> Thanks for all the contributions and using the project!

Major version bump makes sense, hope it goes well. If I have time at a later date, I'll see about our upgrade path and may contribute if needed. Good luck!

**Pull request merged**
